export default function PrivacyPolicy() {
  return (
    <main style={{ background: 'var(--bg)', minHeight: '100vh' }}>
      <div style={{ maxWidth: '760px', margin: '0 auto', padding: '4rem 2rem' }}>
        <a href="/" style={{ fontFamily: 'var(--font-mono)', fontSize: '12px', color: 'var(--text-2)', textDecoration: 'none', display: 'block', marginBottom: '3rem' }}>← Back to XATLAS</a>
        <h1 style={{ fontFamily: 'var(--font-mono)', fontSize: '2rem', fontWeight: 700, color: 'var(--text)', marginBottom: '0.5rem' }}>Privacy Policy</h1>
        <p style={{ fontFamily: 'var(--font-mono)', fontSize: '12px', color: 'var(--text-3)', marginBottom: '3rem' }}>Effective March 23, 2026 · Last updated March 23, 2026</p>
        <div style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 2, display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>1. Introduction</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>XATLAS is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use the XATLAS mobile application and website. This policy complies with the California Consumer Privacy Act (CCPA), the General Data Protection Regulation (GDPR), and other applicable privacy laws.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>2. Information We Collect</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>We collect account email and password, API keys under BYOK architecture, subscription info via Apple, and support communications. We do not collect trading activity, investment decisions, precise geolocation, or financial account numbers. We do not sell your personal information under any circumstances.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>3. How We Store Your API Keys</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>API keys are encrypted at rest using AES-256 encryption, stored exclusively in your device Keychain, never transmitted in plain text, and used only to make authorized requests on your behalf. XATLAS employees cannot access your decrypted API keys. Delete them anytime from Settings.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>4. How We Use Your Information</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>To provide and maintain the Service, process subscriptions, send transactional communications, respond to support, analyze usage to improve features, detect fraud, and comply with legal obligations.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>5. Legal Basis for Processing (GDPR)</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>For EEA users, we process data under: Contract Performance (to provide the Service), Legitimate Interests (improving Service, preventing fraud), Legal Obligation (compliance), and Consent (where applicable, withdrawable at any time).</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>6. How We Share Your Information</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>We do not sell, rent, or trade your data. We share only with service providers bound by confidentiality, Apple for payments, designated third-party data providers, and authorities when legally required.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>7. California Privacy Rights (CCPA)</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>California residents have the right to know what personal information we collect, the right to delete it, the right to opt out of sale (we do not sell data), and the right to non-discrimination for exercising these rights. Submit requests to privacy.xatlas.io with subject "CCPA Request." We respond within 45 days.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>8. European Privacy Rights (GDPR)</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>EEA, UK, and Switzerland users have the right to access, rectify, erase, restrict processing, port data, object to processing, and rights related to automated decision-making. Contact privacy.xatlas.io. We respond within 30 days. You may also lodge a complaint with your local supervisory authority.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>9. Data Retention</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>We retain your information while your account is active. Upon deletion we remove or anonymize your data within 30 days, except where legally required to retain it longer.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>10. Data Breach Notification</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>In the event of a data breach we will notify relevant supervisory authorities within 72 hours (GDPR) and affected users without undue delay if the breach poses high risk to your rights. Notification will be via email and/or prominent in-app notice.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>11. International Data Transfers</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>XATLAS is based in the United States. EEA/UK/Switzerland transfers are made pursuant to Standard Contractual Clauses approved by the European Commission.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>12. Children's Privacy</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>XATLAS is rated 17+ and intended for users 17 and older. We do not knowingly collect data from children under 13. Contact privacy.xatlas.io immediately if you believe this has occurred.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>13. Security</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>We implement AES-256 encryption at rest, TLS 1.3 in transit, iOS Keychain for API keys, regular security assessments, and strict access controls. No transmission method is 100% secure.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>14. Third-Party Services</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>We integrate with Polygon.io, Anthropic, Apple, and FRED. Review their privacy policies at their respective websites.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>15. Changes to This Policy</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>We will notify you of material changes via email and/or in-app notice. Continued use after the effective date constitutes acceptance.</p></div>
          <div><h2 style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', fontWeight: 700, color: 'var(--green)', letterSpacing: '0.08em', marginBottom: '0.75rem', textTransform: 'uppercase' }}>16. Contact Us</h2><p style={{ fontSize: '14px', color: 'var(--text-2)', lineHeight: 1.8 }}>Email: privacy.xatlas.io · Website: xatlas.io · Response time: 30 days (45 days for CCPA)</p></div>
        </div>
      </div>
    </main>
  )
}
